# Generated by Django 2.0.5 on 2019-07-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailvr',
            options={'verbose_name': '邮箱验证码', 'verbose_name_plural': '邮箱验证码'},
        ),
        migrations.AddField(
            model_name='emailvr',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='emailvr',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '未注册')], max_length=10, null=True),
        ),
    ]
